version = 0.1

[default.deploy.parameters]
stack_name = "SeedTrackerStack"
resolve_s3 = true
s3_prefix = "SeedTrackerStack"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
