AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Seed Tracker App

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:

  # Lambda authorizer
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole

  # API Gateway definition with authorizer and stage
  FirebaseApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: FirebaseApi
      StageName: Prod  # 🔧 REQUIRED
      Auth:
        DefaultAuthorizer: Firebase
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          Firebase:
            FunctionArn: !GetAtt AuthFunction.Arn
            Identity:
              Header: Authorization
      Cors:
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'http://44.239.46.70'"
        
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: users.handler
      Runtime: nodejs18.x
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user
            Method: get
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase
        CreateUser:
          Type: Api
          Properties:
            Path: /user
            Method: post
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase
        DeleteUser:
          Type: Api
          Properties:
            Path: /user
            Method: delete
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase

  SeedsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: seeds.handler
      Runtime: nodejs18.x
      Events:
        GetAllSeeds:
          Type: Api
          Properties:
            Path: /seeds/all
            Method: get
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase
        GetUserSeeds:
          Type: Api
          Properties:
            Path: /seeds
            Method: get
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase
        CreateSeed:
          Type: Api
          Properties:
            Path: /seed
            Method: post
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase
        UpdateSeed:
          Type: Api
          Properties:
            Path: /seed
            Method: put
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase
        DeleteSeed:
          Type: Api
          Properties:
            Path: /seed
            Method: delete
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase

  PlantTypesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: planttypes.handler
      Runtime: nodejs18.x
      Events:
        GetPlantTypes:
          Type: Api
          Properties:
            Path: /planttypes/{type}
            Method: get
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase
        GetUniquePlantTypes:
          Type: Api
          Properties:
            Path: /planttypes
            Method: get
            RestApiId: !Ref FirebaseApi
            Auth:
              Authorizer: Firebase